spring.application.name=nextcart-backend

# =========================================================
# SERVER
# =========================================================

server.port=8080
server.address=0.0.0.0


# =========================================================
# SECURITY
# =========================================================

app.security.jwt.secret=${JWT_SECRET}


# =========================================================
# ORDER EXPIRY
# =========================================================

nextcart.order.expiry.fixed-delay-ms=60000


# =========================================================
# DATABASE
# =========================================================

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.oqxwfgxnibifskildvdi
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=600000


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================================================
# RAZORPAY PAYMENT GATEWAY
# =========================================================

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}
razorpay.webhook.secret=${RAZORPAY_WEBHOOK_SECRET}


# =========================================================
# EMAIL / GMAIL SMTP
# =========================================================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# =========================================================
# MSG91
# =========================================================

msg91.auth-key=${MSG91_AUTH_KEY}


# =========================================================
# SUPABASE
# =========================================================

supabase.url=https://oqxwfgxnibifskildvdi.supabase.co
supabase.service-role-key=${SUPABASE_SECRET_KEY}
supabase.kyc-bucket=seller-kyc


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=12MB


# =========================================================
# SELLER VERIFICATION
# =========================================================

# ---------------------------------------------------------
# SANDBOX - PAN KYC
# ---------------------------------------------------------

seller.verification.sandbox.base-url=https://test-api.sandbox.co.in
seller.verification.sandbox.api-key=key_live_c7197bad0252444ca02cfd9e402951b0
seller.verification.sandbox.api-secret=secret_live_776ccd45cec84c61a32067577ab09e17



# ---------------------------------------------------------
# APILAYER NUMVERIFY - MOBILE VERIFICATION
# ---------------------------------------------------------

seller.verification.numverify.base-url=https://apilayer.net/api
seller.verification.numverify.access-key=DKlaCO1Gf6hMnwlKsyunIuk1LjWFkfpU


# ---------------------------------------------------------
# HUNTER.IO - EMAIL VERIFICATION
# ---------------------------------------------------------

seller.verification.hunter.base-url=https://api.hunter.io/v2
seller.verification.hunter.api-key=4fcaf127148f6ad915a7203d9dcc73a3f1f06b5f


# ---------------------------------------------------------
# GST VERIFICATION
# ---------------------------------------------------------

seller.verification.gst.base-url=https://razorpay.com/api